name: Dlang tests

on: [push, pull_request]

jobs:
  main:
    strategy:
      fail-fast: false

      matrix:
        platform: [ debian32 ]
        dc: [ dmd-latest, dmd-2.100.2, dmd-2.103.1, ldc-latest, dmd-master, gdmd, gdmd-12 ]

        include:
          - platform: debian32
            os: ubuntu-24.04
            container: debian:12
            model: 32
            cxx: g++

    runs-on: ${{ matrix.os }}
    container: ${{ matrix.container }}

    steps:
      - uses: actions/checkout@v6

      - name: Install Debian packages
        if: ${{ matrix.platform == 'debian32' }}
        run: |
          dpkg --add-architecture i386
          echo "deb http://deb.debian.org/debian bookworm-backports main contrib non-free" >> /etc/apt/sources.list
          echo "deb-src http://deb.debian.org/debian bookworm-backports main contrib non-free" >> /etc/apt/sources.list
          apt-get -qq update
          apt-get -qq install -y gpg xz-utils 7zip sudo libxml2
          apt-get -qq install -y libc6-dev:i386 libstdc++6:i386 g++:i386

      - name: Install D compiler
        uses: dlang-community/setup-dlang@v2
        with:
          compiler: ${{ matrix.dc }}

      - name: Change env vars to 32-bit
        if: ${{ matrix.platform == 'debian32' }}
        run: |
          echo "LD_LIBRARY_PATH=$(echo "$LD_LIBRARY_PATH" | sed "s|dmd2/linux/lib64|dmd2/linux/lib32|g")" >> "$GITHUB_ENV"
          echo "DC=$(echo "$DC" | sed "s|dmd2/linux/bin64|dmd2/linux/bin32|g")" >> "$GITHUB_ENV"
          echo "$(echo "$PATH" | grep -o "[^:]*dmd2/linux/bin[^:]*" | sed "s|dmd2/linux/bin64|dmd2/linux/bin32|g")" >> "$GITHUB_PATH"

      - name: Print env
        run: |
          env

      - name: 'Build & Test'
        timeout-minutes: 5
        run: |
          ${{ env.DC }} -run runtests.d --github --compiler=${{ env.DC }} --cxx=${{ matrix.cxx }} -m${{ matrix.model }} -v
